html,
body {
    height: 100%;
    background-color: #EDF1F5;
}

body.dark-mode {
    height: 100%;
    background-color: #0B1622;
}

.wrapper {
    min-height: 100%;
    display: flex;
    flex-direction: column;
    background-color: inherit;
}

.preview-box,
.form-box {
    border-radius: 10px;
    background-color: #f8f9fa;
    padding: 20px;
    height: 100%;
    overflow-y: auto;
    border: 2px solid #0d6efd;
}

body.dark-mode .preview-box,
body.dark-mode .form-box {
    background-color: #151F2E;
    border: 2px solid #0d6efd;
}

.form-section {
    padding: 10px;
    border-radius: 10px;
    border: 2px solid #0d6efd;
}

.sortable-container {
    justify-content: space-between;
}

.title-text {
    font-weight: bold;
    color: #0d6efd;
}

.content {
    flex: 1;
}

.sub-text {
    color: #000000;
}

body.dark-mode .sub-text {
    color: #8596A5;
}

.title-text {
    font-weight: bold;
    color: #0d6efd;
}

.dockerfile {
    background-color: #FAFAFA;
    padding: 10px;
    border-radius: 10px;
}

body.dark-mode .dockerfile {
    background-color: #151F2E;
    padding: 10px;
    border-radius: 10px;
}

body.dark-mode .dockerfile-text {
    padding: 10px;
    border-radius: 10px;
}

.main-sub-title {
    font-weight: bold;
    color: #0d6efd;
}

body.dark-mode .text {
    color: #8596A5;
}

.footer {
    background-color: #f8f9fa;
    padding: 10px 0;
    text-align: center;
}

body.dark-mode .footer {
    background-color: #00084D;
    color: #ffffff;
}
