html,
body {
    height: 100%;
    background-color: #EDF1F5;
}

body.dark-mode {
    height: 100%;
    background-color: #0B1622;
}

.wrapper {
    min-height: 100%;
    display: flex;
    flex-direction: column;
    background-color: inherit;
}

.form-box {
    border-radius: 10px;
    background-color: #f8f9fa;
    padding: 20px;
    height: 100%;
    overflow-y: auto;
    border: 2px solid #0d6efd !important;
}

.preview-box {
    top: 0;
    height: 48%;
    border-radius: 10px;
    background-color: #f8f9fa;
    padding: 20px;
    overflow-y: auto;
    border: 2px solid #0d6efd;
}

.dockercompose-title-box {
    position: relative;
    height: 4%;
    display: flex;
    justify-content: center;
}

.dockercompose-box {
    bottom: 0; 
    height: 48%;
    border-radius: 10px;
    background-color: #f8f9fa;
    padding: 20px;
    overflow-y: auto;
    border: 2px solid #0d6efd;
    display: none;
}

body.dark-mode .preview-box,
body.dark-mode .form-box,
body.dark-mode .dockercompose-box {
    background-color: #151F2E;
    border: 2px solid #0d6efd;
}

.dockercompose-title {
    position: absolute;
    top: 18px;
    color: #8596A5;
    display: none;
}

.form-section {
    padding: 10px;
    border-radius: 10px;
    border: 2px solid #0d6efd;
}

.sortable-container {
    justify-content: space-between;
}

.display-4.title-text {
    font-weight: bold;
    color: #0d6efd;
}

.content {
    flex: 1;
}

.sub-text {
    color: #000000;
}

body.dark-mode .sub-text {
    color: #8596A5;
}

.dockerfile {
    background-color: #FAFAFA;
    padding: 10px;
    border-radius: 10px;
}

body.dark-mode .dockerfile {
    background-color: #151F2E;
    padding: 10px;
    border-radius: 10px;
}

.main-sub-title {
    font-weight: bold;
    color: #0d6efd;
}

body.dark-mode .text {
    color: #8596A5;
}

.btn-custom {
    float: right;
    margin-top: -3px;
}

.custom-tooltip {
  --bs-tooltip-bg: #00084D;
  --bs-tooltip-color: #FAFAFA;
--bs-tooltip-opacity: 1;
}

.custom-tooltip {
    --bs-tooltip-bg: #00084D !important;
    --bs-tooltip-color: #FAFAFA !important;
    --bs-tooltip-opacity: 1 !important;
}

.bi {
    float: right; 
    margin-top: -3px; 
    margin-right: 10px; 
    font-size: 1.2rem;
}

.dropdown-menu {
    border: 2px solid #0d6efd;
}

body.dark-mode .dropdown-menu {
    background-color: #151F2E;
    color: #8596A5;
    border: 2px solid #0d6efd;
}

.dropdown-item {
    text-align: center;
    width: 100%;
}

.dropdown-item:hover {
    background-color: #f3f4f5;
}

body.dark-mode .dropdown-item {
    text-align: center;
    background-color: #151F2E;
    color: #8596A5;
    width: 100%;
}

body.dark-mode .dropdown-item:hover {
    background-color: #1c2535;
}