.preview-box,
.form-box {
    border-radius: 10px;
    background-color: #f8f9fa;
    padding: 20px;
    height: 100%;
    overflow-y: auto;
    border: 2px solid #0d6efd;
}

.title-text {
    font-weight: bold;
    color: #0d6efd;
}

.navbar {
    border-bottom: 1px solid #6c757d;
}