version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dir:/dir
      - awaa:ewaeaw
      - dwada:dwadwa
    expose:
      - "80"
    ports:
      - "80:80"
